### ISSUE TITLE
Python3 issue

### ISSUE THREAD

**Issue by ErikThorsell** [zeromq/f77_zmq#10]
I installed ZMQ 4.1.5-1 via the Arch Community repo. I then proceeded by converting your Python script to Python 3 using `2to3`. Running `make` in the examples folder produces the following output:

    gfortran -g -O2 -Wall -Wno-unused -fopenmp hwserver.f -o hwserver libf77zmq.a -lzmq 
    hwserver.f:4:23:

         integer(ZMQ_PTR)        context
                       1
    Error: Symbol  ”zmq_ptr” at (1) has no IMPLICIT-type
    hwserver.f:5:23:

         integer(ZMQ_PTR)        responder
                       1
    Error: Symbol  ”zmq_ptr” at (1) has no IMPLICIT-type
    hwserver.f:14:15:

         context   = f77_zmq_ctx_new()
               1
    Error: Symbol  ”context” at (1) has no IMPLICIT-type
    hwserver.f:15:17:

         responder = f77_zmq_socket(context, ZMQ_REP)
                 1
    Error: Symbol  ”responder” at (1) has no IMPLICIT-type
    hwserver.f:15:51:

         responder = f77_zmq_socket(context, ZMQ_REP)
                                                   1
    Error: Symbol  ”zmq_rep” at (1) has no IMPLICIT-type
    hwserver.f:14:20:

         context   = f77_zmq_ctx_new()
                    1
    Error: Function ”f77_zmq_ctx_new” at (1) has no IMPLICIT-type
    make: *** [Makefile:13: hwserver] Error 1

Any ideas on what this can be?

**Comment by ErikThorsell** [comment]
I removed the f77* files created in the examples folder upon running make. When running `make` f77_zmq.h is created, but it is empty.

**Comment by scemama** [comment]
OK. All these missing types are defined in a file created by the Python script, so
It seems that there is a problem with the Python script which should create the `f77_zmq.h` file. I have never tried it with 2to3.
1) What is your exact version of Python
2) Do you have error messages coming from the Python script before the Fortran compiler gives errors?
3) Are you sure your ZMQ_H environment variable was properly defined?

**Comment by ErikThorsell** [comment]
I was mistaken regarding the usage of the Python script, when running: `python create_f77_zmq_h.py zmq.h` I get the following output:

```
Traceback (most recent call last):
  File "create_f77_zmq_h.py", line 129, in <module>
    main()
  File "create_f77_zmq_h.py", line 117, in main
    create_dict_of_defines(lines,file_out)
  File "create_f77_zmq_h.py", line 61, in create_dict_of_defines
    d['ZMQ_VERSION'] = ZMQ_VERSION_MAJOR*10000 + ZMQ_VERSION_MINOR*100 + ZMQ_VERSION_PATCH
NameError: name 'ZMQ_VERSION_MAJOR' is not defined
```

Still, something seems to be wrong though. Here are the answers to your questions:
1) Python 3.5.1
2) n/a
3) Yes. `echo $ZMQ_H` returns: `/usr/include/zmq.h`

**Comment by scemama** [comment]
It is now solved. There is now a Python3 script in case Python2 is absent.
Thanks for your issue!

**Comment by ErikThorsell** [comment]
I tried running your py3-script and got the following error:
```
Traceback (most recent call last):
  File "create_f77_zmq_h_py3.py", line 130, in <module>
    main()
  File "create_f77_zmq_h_py3.py", line 114, in main
    file_in = open( ZMQ_H, 'r' )
FileNotFoundError: [Errno 2] No such file or directory: 'zmq.h'
```

I created the file myself `touch zmq.h` and got the same error as last time:
```
Traceback (most recent call last):
  File "create_f77_zmq_h_py3.py", line 130, in <module>
    main()
  File "create_f77_zmq_h_py3.py", line 118, in main
    create_dict_of_defines(lines,file_out)
  File "create_f77_zmq_h_py3.py", line 62, in create_dict_of_defines
    d['ZMQ_VERSION'] = int(d['ZMQ_VERSION_MAJOR'])*10000 + int(d['ZMQ_VERSION_MINOR'])*100 + int(d['ZMQ_VERSION_PATCH'])
KeyError: 'ZMQ_VERSION_MAJOR'
```
`echo $ZMQ_H` returns: `/usr/include/zmq.h`

**Comment by scemama** [comment]
You shouldn't run the python3 script by yourself.
The makefile first copies the `ZMQ_H` file in the current directory. Then it tries to run the Python2 script, and if it fails it will then run the Python3 one to build the file named `f77_zmq.h`.

So if you want to run the Python3 script by hand, you can copy the `/usr/include/zmq.h` file in the current directory, and then run the Python script.

**Comment by ErikThorsell** [comment]
I was indeed able to copy the file and run the python script. However, running `make` does not seem to work, I had to run the python script on its own and then run make to create the libs.

I ran some of your examples and they seem to be working. Thank you so much for your help!

**Comment by scemama** [comment]
Great! I'll fix the makefile then.
