### ISSUE TITLE
f77_zmq build error

### ISSUE THREAD

**Issue by tbhuber** [zeromq/f77_zmq#23]
I am trying to build zeromq and the fortran binding on a mac Catalina 10.15 for a program called 'quantum_package'

After successfully building zeromq (4.3.2), setting the environmental variable ZMQ_H, and executing the command $make, I obtain the following error. The error implies that a modification needs to be made in the encrypted f77_zmq.o file. I found a f77_zmq 4.3.2, but I obtain the same error. Any assistance would be greatly appreciated. python3 is indeed installed.

gcc -fPIC -shared f77_zmq.o -o libf77zmq.so
Undefined symbols for architecture x86_64:
  "_zmq_bind", referenced from:
      _f77_zmq_bind_ in f77_zmq.o
     (maybe you meant: _f77_zmq_bind_)
  "_zmq_close", referenced from:
      _f77_zmq_close_ in f77_zmq.o
     (maybe you meant: _f77_zmq_close_)
  "_zmq_connect", referenced from:
      _f77_zmq_connect_ in f77_zmq.o
     (maybe you meant: _f77_zmq_connect_)
  "_zmq_ctx_destroy", referenced from:
      _f77_zmq_ctx_destroy_ in f77_zmq.o
     (maybe you meant: _f77_zmq_ctx_destroy_)
  "_zmq_ctx_get", referenced from:
      _f77_zmq_ctx_get_ in f77_zmq.o
     (maybe you meant: _f77_zmq_ctx_get_)
  "_zmq_ctx_new", referenced from:
      _f77_zmq_ctx_new_ in f77_zmq.o
     (maybe you meant: _f77_zmq_ctx_new_)
  "_zmq_ctx_set", referenced from:
      _f77_zmq_ctx_set_ in f77_zmq.o
     (maybe you meant: _f77_zmq_ctx_set_)
  "_zmq_ctx_shutdown", referenced from:
      _f77_zmq_ctx_shutdown_ in f77_zmq.o
     (maybe you meant: _f77_zmq_ctx_shutdown_)
  "_zmq_ctx_term", referenced from:
      _f77_zmq_ctx_term_ in f77_zmq.o
     (maybe you meant: _f77_zmq_ctx_term_)
  "_zmq_disconnect", referenced from:
      _f77_zmq_disconnect_ in f77_zmq.o
     (maybe you meant: _f77_zmq_disconnect_)
  "_zmq_errno", referenced from:
      _f77_zmq_errno_ in f77_zmq.o
     (maybe you meant: _f77_zmq_errno_)
  "_zmq_getsockopt", referenced from:
      _f77_zmq_getsockopt_ in f77_zmq.o
     (maybe you meant: _f77_zmq_getsockopt_)
  "_zmq_msg_close", referenced from:
      _f77_zmq_msg_close_ in f77_zmq.o
     (maybe you meant: _f77_zmq_msg_close_)
  "_zmq_msg_copy", referenced from:
      _f77_zmq_msg_copy_ in f77_zmq.o
     (maybe you meant: _f77_zmq_msg_copy_, _f77_zmq_msg_copy_from_data_ , _f77_zmq_msg_copy_to_data8_ , _f77_zmq_msg_copy_to_data_ )
  "_zmq_msg_data", referenced from:
      _f77_zmq_msg_data_ in f77_zmq.o
      _f77_zmq_msg_copy_from_data_ in f77_zmq.o
      _f77_zmq_msg_copy_to_data_ in f77_zmq.o
      _f77_zmq_msg_copy_to_data8_ in f77_zmq.o
     (maybe you meant: _f77_zmq_msg_data_new_, _f77_zmq_msg_data_ )
  "_zmq_msg_get", referenced from:
      _f77_zmq_msg_get_ in f77_zmq.o
     (maybe you meant: _f77_zmq_msg_gets_, _f77_zmq_msg_get_ )
  "_zmq_msg_gets", referenced from:
      _f77_zmq_msg_gets_ in f77_zmq.o
     (maybe you meant: _f77_zmq_msg_gets_)
  "_zmq_msg_init", referenced from:
      _f77_zmq_msg_init_ in f77_zmq.o
     (maybe you meant: _f77_zmq_msg_init_data_, _f77_zmq_msg_init_ , _f77_zmq_msg_init_size_ )
  "_zmq_msg_init_data", referenced from:
      _f77_zmq_msg_init_data_ in f77_zmq.o
     (maybe you meant: _f77_zmq_msg_init_data_)
  "_zmq_msg_init_size", referenced from:
      _f77_zmq_msg_init_size_ in f77_zmq.o
     (maybe you meant: _f77_zmq_msg_init_size_)
  "_zmq_msg_more", referenced from:
      _f77_zmq_msg_more_ in f77_zmq.o
     (maybe you meant: _f77_zmq_msg_more_)
  "_zmq_msg_move", referenced from:
      _f77_zmq_msg_move_ in f77_zmq.o
     (maybe you meant: _f77_zmq_msg_move_)
  "_zmq_msg_recv", referenced from:
      _f77_zmq_msg_recv_ in f77_zmq.o
      _f77_zmq_msg_recv8_ in f77_zmq.o
     (maybe you meant: _f77_zmq_msg_recv_, _f77_zmq_msg_recv8_ )
  "_zmq_msg_send", referenced from:
      _f77_zmq_msg_send_ in f77_zmq.o
      _f77_zmq_msg_send8_ in f77_zmq.o
     (maybe you meant: _f77_zmq_msg_send8_, _f77_zmq_msg_send_ )
  "_zmq_msg_set", referenced from:
      _f77_zmq_msg_set_ in f77_zmq.o
     (maybe you meant: _f77_zmq_msg_set_)
  "_zmq_msg_size", referenced from:
      _f77_zmq_msg_size_ in f77_zmq.o
      _f77_zmq_msg_size8_ in f77_zmq.o
      _f77_zmq_msg_copy_from_data_ in f77_zmq.o
     (maybe you meant: _f77_zmq_msg_size8_, _f77_zmq_msg_size_ )
  "_zmq_poll", referenced from:
      _f77_zmq_poll_ in f77_zmq.o
     (maybe you meant: _f77_zmq_pollitem_revents_, _f77_zmq_pollitem_set_socket_ , _f77_zmq_pollitem_new_ , _f77_zmq_pollitem_destroy_ , _f77_zmq_pollitem_set_events_ , _f77_zmq_poll_ )
  "_zmq_proxy", referenced from:
      _f77_zmq_proxy_ in f77_zmq.o
     (maybe you meant: _f77_zmq_proxy_, _f77_zmq_proxy_steerable_ )
  "_zmq_proxy_steerable", referenced from:
      _f77_zmq_proxy_steerable_ in f77_zmq.o
     (maybe you meant: _f77_zmq_proxy_steerable_)
  "_zmq_recv", referenced from:
      _f77_zmq_recv_ in f77_zmq.o
      _f77_zmq_recv8_ in f77_zmq.o
     (maybe you meant: _f77_zmq_recv8_, _f77_zmq_recv_ )
  "_zmq_send", referenced from:
      _f77_zmq_send_ in f77_zmq.o
      _f77_zmq_send8_ in f77_zmq.o
     (maybe you meant: _f77_zmq_send_const8_, _f77_zmq_send8_ , _f77_zmq_send_const_ , _f77_zmq_send_ )
  "_zmq_send_const", referenced from:
      _f77_zmq_send_const_ in f77_zmq.o
      _f77_zmq_send_const8_ in f77_zmq.o
     (maybe you meant: _f77_zmq_send_const8_, _f77_zmq_send_const_ )
  "_zmq_setsockopt", referenced from:
      _f77_zmq_setsockopt_ in f77_zmq.o
     (maybe you meant: _f77_zmq_setsockopt_)
  "_zmq_socket", referenced from:
      _f77_zmq_socket_ in f77_zmq.o
     (maybe you meant: _f77_zmq_socket_monitor_, _f77_zmq_socket_ )
  "_zmq_socket_monitor", referenced from:
      _f77_zmq_socket_monitor_ in f77_zmq.o
     (maybe you meant: _f77_zmq_socket_monitor_)
  "_zmq_strerror", referenced from:
      _f77_zmq_strerror_ in f77_zmq.o
     (maybe you meant: _f77_zmq_strerror_)
  "_zmq_term", referenced from:
      _f77_zmq_term_ in f77_zmq.o
     (maybe you meant: _f77_zmq_term_)
  "_zmq_unbind", referenced from:
      _f77_zmq_unbind_ in f77_zmq.o
     (maybe you meant: _f77_zmq_unbind_)
  "_zmq_version", referenced from:
      _f77_zmq_version_ in f77_zmq.o
     (maybe you meant: _f77_zmq_version_)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [libf77zmq.so] Error 1

**Comment by scemama** [comment]
Hi,
yes, the Fortran binding is a bit outdated and doesn't work on MacOS
because the conventions in underscores between C and Fortran are not the
same as on Linux. It was written before iso_c_binding appeared in Fortran.

I don't have time to rewrite the zeromq binding to make it
platform-independent, but if you are willing to do it, I will be happy
to help. I think zeromq needs a new fortran interface.

If you really want to run on a mac, the simplest would be to install a
virtual machine or a container with a Linux inside.

best,

Anthony

tbhuber writes:

> I am trying to build zeromq and the fortran binding on a mac Catalina 10.15 for a program called 'quantum_package'
>
> After successfully building zeromq (4.3.2), setting the environmental variable ZMQ_H, and executing the command $make, I obtain the following error. The error implies that a modification needs to be made in the encrypted f77_zmq.o file. I found a f77_zmq 4.3.2, but I obtain the same error. Any assistance would be greatly appreciated. python3 is indeed installed.
>
>
> gcc -fPIC -shared f77_zmq.o -o libf77zmq.so
> Undefined symbols for architecture x86_64:
>   "_zmq_bind", referenced from:
>       _f77_zmq_bind_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_bind_)
>   "_zmq_close", referenced from:
>       _f77_zmq_close_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_close_)
>   "_zmq_connect", referenced from:
>       _f77_zmq_connect_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_connect_)
>   "_zmq_ctx_destroy", referenced from:
>       _f77_zmq_ctx_destroy_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_ctx_destroy_)
>   "_zmq_ctx_get", referenced from:
>       _f77_zmq_ctx_get_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_ctx_get_)
>   "_zmq_ctx_new", referenced from:
>       _f77_zmq_ctx_new_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_ctx_new_)
>   "_zmq_ctx_set", referenced from:
>       _f77_zmq_ctx_set_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_ctx_set_)
>   "_zmq_ctx_shutdown", referenced from:
>       _f77_zmq_ctx_shutdown_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_ctx_shutdown_)
>   "_zmq_ctx_term", referenced from:
>       _f77_zmq_ctx_term_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_ctx_term_)
>   "_zmq_disconnect", referenced from:
>       _f77_zmq_disconnect_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_disconnect_)
>   "_zmq_errno", referenced from:
>       _f77_zmq_errno_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_errno_)
>   "_zmq_getsockopt", referenced from:
>       _f77_zmq_getsockopt_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_getsockopt_)
>   "_zmq_msg_close", referenced from:
>       _f77_zmq_msg_close_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_msg_close_)
>   "_zmq_msg_copy", referenced from:
>       _f77_zmq_msg_copy_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_msg_copy_, _f77_zmq_msg_copy_from_data_ , _f77_zmq_msg_copy_to_data8_ , _f77_zmq_msg_copy_to_data_ )
>   "_zmq_msg_data", referenced from:
>       _f77_zmq_msg_data_ in f77_zmq.o
>       _f77_zmq_msg_copy_from_data_ in f77_zmq.o
>       _f77_zmq_msg_copy_to_data_ in f77_zmq.o
>       _f77_zmq_msg_copy_to_data8_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_msg_data_new_, _f77_zmq_msg_data_ )
>   "_zmq_msg_get", referenced from:
>       _f77_zmq_msg_get_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_msg_gets_, _f77_zmq_msg_get_ )
>   "_zmq_msg_gets", referenced from:
>       _f77_zmq_msg_gets_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_msg_gets_)
>   "_zmq_msg_init", referenced from:
>       _f77_zmq_msg_init_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_msg_init_data_, _f77_zmq_msg_init_ , _f77_zmq_msg_init_size_ )
>   "_zmq_msg_init_data", referenced from:
>       _f77_zmq_msg_init_data_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_msg_init_data_)
>   "_zmq_msg_init_size", referenced from:
>       _f77_zmq_msg_init_size_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_msg_init_size_)
>   "_zmq_msg_more", referenced from:
>       _f77_zmq_msg_more_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_msg_more_)
>   "_zmq_msg_move", referenced from:
>       _f77_zmq_msg_move_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_msg_move_)
>   "_zmq_msg_recv", referenced from:
>       _f77_zmq_msg_recv_ in f77_zmq.o
>       _f77_zmq_msg_recv8_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_msg_recv_, _f77_zmq_msg_recv8_ )
>   "_zmq_msg_send", referenced from:
>       _f77_zmq_msg_send_ in f77_zmq.o
>       _f77_zmq_msg_send8_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_msg_send8_, _f77_zmq_msg_send_ )
>   "_zmq_msg_set", referenced from:
>       _f77_zmq_msg_set_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_msg_set_)
>   "_zmq_msg_size", referenced from:
>       _f77_zmq_msg_size_ in f77_zmq.o
>       _f77_zmq_msg_size8_ in f77_zmq.o
>       _f77_zmq_msg_copy_from_data_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_msg_size8_, _f77_zmq_msg_size_ )
>   "_zmq_poll", referenced from:
>       _f77_zmq_poll_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_pollitem_revents_, _f77_zmq_pollitem_set_socket_ , _f77_zmq_pollitem_new_ , _f77_zmq_pollitem_destroy_ , _f77_zmq_pollitem_set_events_ , _f77_zmq_poll_ )
>   "_zmq_proxy", referenced from:
>       _f77_zmq_proxy_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_proxy_, _f77_zmq_proxy_steerable_ )
>   "_zmq_proxy_steerable", referenced from:
>       _f77_zmq_proxy_steerable_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_proxy_steerable_)
>   "_zmq_recv", referenced from:
>       _f77_zmq_recv_ in f77_zmq.o
>       _f77_zmq_recv8_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_recv8_, _f77_zmq_recv_ )
>   "_zmq_send", referenced from:
>       _f77_zmq_send_ in f77_zmq.o
>       _f77_zmq_send8_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_send_const8_, _f77_zmq_send8_ , _f77_zmq_send_const_ , _f77_zmq_send_ )
>   "_zmq_send_const", referenced from:
>       _f77_zmq_send_const_ in f77_zmq.o
>       _f77_zmq_send_const8_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_send_const8_, _f77_zmq_send_const_ )
>   "_zmq_setsockopt", referenced from:
>       _f77_zmq_setsockopt_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_setsockopt_)
>   "_zmq_socket", referenced from:
>       _f77_zmq_socket_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_socket_monitor_, _f77_zmq_socket_ )
>   "_zmq_socket_monitor", referenced from:
>       _f77_zmq_socket_monitor_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_socket_monitor_)
>   "_zmq_strerror", referenced from:
>       _f77_zmq_strerror_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_strerror_)
>   "_zmq_term", referenced from:
>       _f77_zmq_term_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_term_)
>   "_zmq_unbind", referenced from:
>       _f77_zmq_unbind_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_unbind_)
>   "_zmq_version", referenced from:
>       _f77_zmq_version_ in f77_zmq.o
>      (maybe you meant: _f77_zmq_version_)
> ld: symbol(s) not found for architecture x86_64
> collect2: error: ld returned 1 exit status
> make: *** [libf77zmq.so] Error 1

**Comment by tbhuber** [comment]
I appreciate the response. At this time i do not believe that i am experienced enough to write this code. Maybe in the future i will revisit this issue.
